layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: pallab-gain-4a0ba868
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: WebRTC
    web_url: https://webrtc.org/
    image_url: https://webrtc.org/assets/images/webrtc-logo-vert-retro-dist.svg

  - name: Node.js
    web_url: https://nodejs.org/en/
    image_url: https://nodejs.org/static/images/logo.svg

  - name: Golang
    web_url: https://golang.org/
    image_url: https://golang.org/doc/gopher/doc.png
